"""Wrapping detection checked against an independent brute-force calculation.

Wrapping is easy to get subtly wrong.  The natural shortcut — delete the
boundary-closing bonds along an axis and ask whether any deleted bond rejoins a
cluster to itself — detects only cycles that cross the boundary once, and
silently misses clusters that wind using several crossings.  These tests pin
the production implementation to an independent spanning-forest calculation so
that the shortcut cannot creep back in.
"""

from collections import deque

import numpy as np
import pytest

from rbim.clusters import activate_bonds, label_and_wrap
from rbim.disorder import generate_disorder
from rbim.lattice import build_lattice, couplings_from_disorder
from rbim.swendsen_wang import random_spins, sw_sweep


def brute_force_winding(active, lattice):
    """Independent oracle: BFS spanning forest, then every fundamental cycle.

    Each site is assigned an unwrapped position by breadth-first search.  Every
    non-tree active bond closes exactly one fundamental cycle, and the cycles of
    a graph are generated by those, so checking each one is exhaustive.
    """
    n_sites = lattice.n_sites
    neighbours = [[] for _ in range(n_sites)]
    for k in np.flatnonzero(active):
        a, b = int(lattice.bonds[k, 0]), int(lattice.bonds[k, 1])
        dx, dy = int(lattice.bond_dx[k]), int(lattice.bond_dy[k])
        neighbours[a].append((b, dx, dy, int(k)))
        neighbours[b].append((a, -dx, -dy, int(k)))

    position = {}
    tree_bonds = set()
    for start in range(n_sites):
        if start in position:
            continue
        position[start] = (0, 0)
        queue = deque([start])
        while queue:
            node = queue.popleft()
            nx, ny = position[node]
            for neighbour, dx, dy, k in neighbours[node]:
                if neighbour not in position:
                    position[neighbour] = (nx + dx, ny + dy)
                    tree_bonds.add(k)
                    queue.append(neighbour)

    wraps_x = wraps_y = False
    for k in np.flatnonzero(active):
        k = int(k)
        if k in tree_bonds:
            continue
        a, b = int(lattice.bonds[k, 0]), int(lattice.bonds[k, 1])
        dx, dy = int(lattice.bond_dx[k]), int(lattice.bond_dy[k])
        if position[a][0] + dx - position[b][0] != 0:
            wraps_x = True
        if position[a][1] + dy - position[b][1] != 0:
            wraps_y = True
    return wraps_x, wraps_y


def _sample_configurations(sizes, disorders, temperatures, n_samples, seed=0):
    """Yield (lattice, active) pairs drawn from equilibrated-ish configurations."""
    rng = np.random.default_rng(seed)
    for L in sizes:
        lattice = build_lattice(L)
        for p in disorders:
            J_h, J_v = generate_disorder(L, p, rng)
            J = couplings_from_disorder(J_h, J_v)
            for temperature in temperatures:
                spins = random_spins(lattice.n_sites, rng)
                beta = 1.0 / temperature
                for _ in range(n_samples):
                    sw_sweep(spins, lattice, J, beta, rng, measure=False)
                    yield lattice, activate_bonds(spins, lattice, J, beta, rng)


def test_wrapping_matches_brute_force():
    checked = 0
    wrapping_seen = 0
    for lattice, active in _sample_configurations(
        sizes=(3, 6, 10), disorders=(0.0, 0.1, 0.5), temperatures=(1.0, 2.27, 4.0), n_samples=4
    ):
        expected = brute_force_winding(active, lattice)
        _, _, wraps_x, wraps_y = label_and_wrap(active, lattice)
        assert (bool(wraps_x), bool(wraps_y)) == expected
        checked += 1
        wrapping_seen += int(any(expected))

    # Guard against a vacuous pass: the sample must actually contain wrapping.
    assert checked > 50
    assert wrapping_seen > 5


@pytest.mark.slow
def test_wrapping_matches_brute_force_on_larger_lattices():
    for lattice, active in _sample_configurations(
        sizes=(16, 24), disorders=(0.0, 0.2), temperatures=(1.2, 2.27), n_samples=6, seed=17
    ):
        expected = brute_force_winding(active, lattice)
        _, _, wraps_x, wraps_y = label_and_wrap(active, lattice)
        assert (bool(wraps_x), bool(wraps_y)) == expected


def test_labels_partition_the_lattice():
    for lattice, active in _sample_configurations(
        sizes=(6, 10), disorders=(0.1,), temperatures=(1.5,), n_samples=3, seed=5
    ):
        n_clusters, labels, _, _ = label_and_wrap(active, lattice)
        assert labels.min() == 0
        assert labels.max() == n_clusters - 1
        assert np.bincount(labels, minlength=n_clusters).sum() == lattice.n_sites
        # Every active bond must join two sites of the same cluster.
        ends = lattice.bonds[active]
        assert np.all(labels[ends[:, 0]] == labels[ends[:, 1]])
